# Generated by Django 2.2.4 on 2019-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetail',
            name='registration_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
