# Generated by Django 2.2.4 on 2019-09-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190917_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetail',
            name='display_registration_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='registration_type',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
