# Generated by Django 2.2.4 on 2019-11-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190919_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_table', models.TextField(blank=True, null=True)),
                ('display_schedule_table', models.BooleanField(default=True)),
            ],
        ),
    ]
